# Generated by Django 2.2 on 2019-05-10 22:52

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0006_auto_20190407_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=martor.models.MartorField(),
        ),
    ]
