# Generated by Django 2.2 on 2019-05-10 23:10

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_auto_20190510_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
